//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International_Travel_Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel_table
    {
        public int Travel_Id { get; set; }
        public string Currency_ISO_Code { get; set; }
        public System.DateTime Travel_timestamp { get; set; }
        public decimal Travel_Price_Amount_in_payment_currency { get; set; }
        public string Status { get; set; }
    }
}
